#!/usr/bin/env python3
"""Fetch top N movies per year from TMDb and emit a C header/source pair
for the Zeal Movie Hangman game.

Requires a free TMDb API key: https://www.themoviedb.org/settings/api
Pass it via --api-key or the TMDB_API_KEY environment variable.

Usage:
    python3 tools/fetch_movies.py --start-year 2001 --end-year 2025 --count 10
"""
import argparse
import os
import re
import sys
import time
import urllib.request
import urllib.parse
import json

TMDB_DISCOVER_URL = "https://api.themoviedb.org/3/discover/movie"

# The in-game on-screen keyboard only has tiles for A-Z (see img/tileset),
# so titles must be reduced to that alphabet plus spaces.
VALID_CHARS_RE = re.compile(r"[^A-Z ]")
MAX_TITLE_LEN = 20


def sanitize_title(title: str) -> str | None:
    upper = title.upper()
    # Drop common punctuation outright rather than turning it into a space.
    upper = upper.replace("'", "").replace("’", "")
    # Anything else non-alphabetic (digits, colons, hyphens, accents...) becomes a space.
    cleaned = VALID_CHARS_RE.sub(" ", upper)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    if not cleaned or len(cleaned) > MAX_TITLE_LEN:
        return None
    return cleaned


def fetch_year(api_key: str, year: int, count: int, min_votes: int) -> list[str]:
    chosen: list[str] = []
    seen: set[str] = set()
    for page in range(1, 6):  # up to 5 pages (100 candidates) per year
        if len(chosen) >= count:
            break
        params = {
            "api_key": api_key,
            "sort_by": "revenue.desc",
            "primary_release_year": str(year),
            "vote_count.gte": str(min_votes),
            "page": str(page),
        }
        url = f"{TMDB_DISCOVER_URL}?{urllib.parse.urlencode(params)}"
        with urllib.request.urlopen(url) as resp:
            data = json.load(resp)
        results = data.get("results", [])
        if not results:
            break
        for movie in results:
            title = sanitize_title(movie.get("title", ""))
            if title and title not in seen:
                seen.add(title)
                chosen.append(title)
            if len(chosen) >= count:
                break
        time.sleep(0.05)  # be polite to the API
    return chosen


def write_header(path: str):
    with open(path, "w") as f:
        f.write(
            """// Auto-generated by tools/fetch_movies.py - do not edit by hand.
#ifndef MOVIES_H
#define MOVIES_H

#include <stdint.h>

typedef struct {
    uint16_t year;
    const char *title;
} movie_entry_t;

extern const movie_entry_t movies[];
extern const uint16_t movies_count;

#endif // MOVIES_H
"""
        )


def write_source(path: str, entries: list[tuple[int, str]]):
    with open(path, "w") as f:
        f.write('// Auto-generated by tools/fetch_movies.py - do not edit by hand.\n')
        f.write('#include "movies.h"\n\n')
        f.write("const movie_entry_t movies[] = {\n")
        for year, title in entries:
            f.write(f'    {{ {year}, "{title}" }},\n')
        f.write("};\n\n")
        f.write(f"const uint16_t movies_count = {len(entries)};\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--api-key", default=os.environ.get("TMDB_API_KEY"))
    parser.add_argument("--start-year", type=int, default=2001)
    parser.add_argument("--end-year", type=int, default=2025)
    parser.add_argument("--count", type=int, default=10, help="movies per year")
    parser.add_argument("--min-votes", type=int, default=200)
    parser.add_argument("--out-dir", default="src")
    args = parser.parse_args()

    if not args.api_key:
        print("Error: TMDb API key required (--api-key or TMDB_API_KEY env var).", file=sys.stderr)
        sys.exit(1)

    entries: list[tuple[int, str]] = []
    for year in range(args.start_year, args.end_year + 1):
        titles = fetch_year(args.api_key, year, args.count, args.min_votes)
        print(f"{year}: {len(titles)} movies -> {titles}")
        entries.extend((year, t) for t in titles)

    header_path = os.path.join(args.out_dir, "movies.h")
    source_path = os.path.join(args.out_dir, "movies.c")
    write_header(header_path)
    write_source(source_path, entries)
    print(f"\nWrote {header_path} and {source_path} ({len(entries)} total movies)")


if __name__ == "__main__":
    main()
