// Auto-generated by tools/fetch_movies.py - do not edit by hand.
#ifndef MOVIES_H
#define MOVIES_H

#include <stdint.h>

typedef struct {
    uint16_t year;
    const char *title;
} movie_entry_t;

extern const movie_entry_t movies[];
extern const uint16_t movies_count;

#endif // MOVIES_H
